apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vproapp.name }} #vproapp
spec:
  selector:
    matchLabels:
      app: {{ .Values.vproapp.name }} #vproapp
  replicas: {{ .Values.replicaCount }} #1
  template:
    metadata:
      labels:
        app: {{ .Values.vproapp.name }} #vproapp
    spec:
      containers:
      - name: {{ .Values.vproapp.name }} #vproapp
        image: {{ .Values.vproapp.container.image }} #ishfak00/nproweb:tomcat_9.0-jre11_vproapp
        ports:
        - name: vproapp-port
          containerPort: {{ .Values.vproapp.container.port }} #8080
      initContainers:
      - name: init-mydb
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup vprodb; do echo waiting for mydb; sleep 2; done"]

      - name: init-mymemcache
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup vprocache01; do echo waiting for mymemcache; sleep 2; done"]


---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vproapp.name }} #vproapp
spec:
  type: {{ .Values.vproapp.service.type }}
  selector:
    app: {{ .Values.vproapp.name }} #vproapp
  ports:
  - port: {{ .Values.vproapp.service.port }}
    targetPort:  {{ .Values.vproapp.container.port }} #vproapp-port
    protocol: TCP
